# Generated by Django 2.2.3 on 2019-08-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdat',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='em',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='psw',
            new_name='password',
        ),
    ]
