# Generated by Django 2.2.3 on 2019-08-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_id_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_admin',
        ),
    ]
