# Generated by Django 2.2.3 on 2019-08-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
